gcc:
  path: /usr/bin/gcc
  default_flags : ["-Wall", -Wextra]

g++:
  path: /usr/bin/g++
  default_flags : ["-Wall", "-Wextra", "-std=c++17"]

verilator:
  path: /usr/bin/verilator
  default_flags : []

ar:
  path: /usr/bin/ar
  default_flags : []
